/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Bai3;

import javax.swing.JOptionPane;

/**
 *
 * @author GIA KIET
 */
public class Bai3 extends javax.swing.JFrame {

    public Bai3() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jSeparator2 = new javax.swing.JSeparator();
        jPanel3 = new javax.swing.JPanel();
        LabelToolbar = new javax.swing.JLabel();
        ExitBtn = new javax.swing.JButton();
        jToolBar1 = new javax.swing.JToolBar();
        openFileBtn = new javax.swing.JButton();
        SaveFileBtn = new javax.swing.JButton();
        SaveAsFilebtn = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        PrintFilebtn = new javax.swing.JButton();
        Picturebtn = new javax.swing.JButton();
        Socialbtn = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        AddFileBtn = new javax.swing.JButton();
        SignInBtn = new javax.swing.JButton();
        ZoomingBtn = new javax.swing.JButton();
        UseCursorBtn = new javax.swing.JButton();
        HighlightBtn = new javax.swing.JButton();
        CaptureBtn = new javax.swing.JButton();
        SecurityBtn = new javax.swing.JButton();
        UsePencilBtn = new javax.swing.JButton();

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAutoRequestFocus(false);
        setBackground(new java.awt.Color(144, 224, 239));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel2.setBackground(new java.awt.Color(185, 243, 252));

        jSeparator2.setForeground(new java.awt.Color(174, 226, 255));

        jPanel3.setBackground(new java.awt.Color(147, 198, 231));

        LabelToolbar.setFont(new java.awt.Font("MV Boli", 1, 18)); // NOI18N
        LabelToolbar.setText("Basic");

        ExitBtn.setBackground(new java.awt.Color(144, 224, 239));
        ExitBtn.setText("X");
        ExitBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ExitBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(LabelToolbar, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(ExitBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(LabelToolbar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(ExitBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        jToolBar1.setBackground(new java.awt.Color(185, 243, 252));
        jToolBar1.setRollover(true);

        openFileBtn.setBackground(new java.awt.Color(185, 243, 252));
        openFileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/open_file.png"))); // NOI18N
        openFileBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        openFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                openFileBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(openFileBtn);

        SaveFileBtn.setBackground(new java.awt.Color(185, 243, 252));
        SaveFileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/save.png"))); // NOI18N
        SaveFileBtn.setFocusable(false);
        SaveFileBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SaveFileBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        SaveFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveFileBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(SaveFileBtn);

        SaveAsFilebtn.setBackground(new java.awt.Color(185, 243, 252));
        SaveAsFilebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/save_as.png"))); // NOI18N
        SaveAsFilebtn.setFocusable(false);
        SaveAsFilebtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SaveAsFilebtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        SaveAsFilebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SaveAsFilebtnActionPerformed(evt);
            }
        });
        jToolBar1.add(SaveAsFilebtn);

        jSeparator1.setBackground(new java.awt.Color(0, 119, 182));
        jSeparator1.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jSeparator1.setForeground(new java.awt.Color(0, 119, 182));
        jToolBar1.add(jSeparator1);

        PrintFilebtn.setBackground(new java.awt.Color(185, 243, 252));
        PrintFilebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/print.png"))); // NOI18N
        PrintFilebtn.setFocusable(false);
        PrintFilebtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        PrintFilebtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        PrintFilebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PrintFilebtnActionPerformed(evt);
            }
        });
        jToolBar1.add(PrintFilebtn);

        Picturebtn.setBackground(new java.awt.Color(185, 243, 252));
        Picturebtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/picture.png"))); // NOI18N
        Picturebtn.setFocusable(false);
        Picturebtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Picturebtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Picturebtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                PicturebtnActionPerformed(evt);
            }
        });
        jToolBar1.add(Picturebtn);

        Socialbtn.setBackground(new java.awt.Color(185, 243, 252));
        Socialbtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/fb.png"))); // NOI18N
        Socialbtn.setFocusable(false);
        Socialbtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        Socialbtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        Socialbtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SocialbtnActionPerformed(evt);
            }
        });
        jToolBar1.add(Socialbtn);

        jSeparator3.setBackground(new java.awt.Color(0, 119, 182));
        jSeparator3.setBorder(javax.swing.BorderFactory.createCompoundBorder());
        jSeparator3.setForeground(new java.awt.Color(0, 119, 182));
        jToolBar1.add(jSeparator3);

        AddFileBtn.setBackground(new java.awt.Color(185, 243, 252));
        AddFileBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/computer.png"))); // NOI18N
        AddFileBtn.setFocusable(false);
        AddFileBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        AddFileBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        AddFileBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                AddFileBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(AddFileBtn);

        SignInBtn.setBackground(new java.awt.Color(185, 243, 252));
        SignInBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/raise_hand.png"))); // NOI18N
        SignInBtn.setFocusable(false);
        SignInBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SignInBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        SignInBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SignInBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(SignInBtn);

        ZoomingBtn.setBackground(new java.awt.Color(185, 243, 252));
        ZoomingBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/zooming.png"))); // NOI18N
        ZoomingBtn.setFocusable(false);
        ZoomingBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        ZoomingBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        ZoomingBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ZoomingBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(ZoomingBtn);

        UseCursorBtn.setBackground(new java.awt.Color(185, 243, 252));
        UseCursorBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/cursor.png"))); // NOI18N
        UseCursorBtn.setFocusable(false);
        UseCursorBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        UseCursorBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        UseCursorBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UseCursorBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(UseCursorBtn);

        HighlightBtn.setBackground(new java.awt.Color(185, 243, 252));
        HighlightBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/highlight.png"))); // NOI18N
        HighlightBtn.setFocusable(false);
        HighlightBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        HighlightBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        HighlightBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                HighlightBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(HighlightBtn);

        CaptureBtn.setBackground(new java.awt.Color(185, 243, 252));
        CaptureBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/camera.png"))); // NOI18N
        CaptureBtn.setFocusable(false);
        CaptureBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        CaptureBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        CaptureBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CaptureBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(CaptureBtn);

        SecurityBtn.setBackground(new java.awt.Color(185, 243, 252));
        SecurityBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/icons8-lock-error-48.png"))); // NOI18N
        SecurityBtn.setFocusable(false);
        SecurityBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        SecurityBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        SecurityBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                SecurityBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(SecurityBtn);

        UsePencilBtn.setBackground(new java.awt.Color(185, 243, 252));
        UsePencilBtn.setIcon(new javax.swing.ImageIcon(getClass().getResource("/resources/pencil.png"))); // NOI18N
        UsePencilBtn.setFocusable(false);
        UsePencilBtn.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        UsePencilBtn.setVerticalTextPosition(javax.swing.SwingConstants.BOTTOM);
        UsePencilBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                UsePencilBtnActionPerformed(evt);
            }
        });
        jToolBar1.add(UsePencilBtn);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jSeparator2)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator2, javax.swing.GroupLayout.PREFERRED_SIZE, 4, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ExitBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ExitBtnActionPerformed
        // TODO add your handling code here:
        int option = JOptionPane.showConfirmDialog(this, "Do you want to exit?", "Exit Form",JOptionPane.YES_OPTION, JOptionPane.QUESTION_MESSAGE);
        if(option == JOptionPane.YES_OPTION){
            System .exit(0);
        }
    }//GEN-LAST:event_ExitBtnActionPerformed

    private void SecurityBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SecurityBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Security Settings");
    }//GEN-LAST:event_SecurityBtnActionPerformed

    private void openFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_openFileBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "You clicked open file");
    }//GEN-LAST:event_openFileBtnActionPerformed

    private void SaveFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveFileBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "You clicked save file with your latest changes");
    }//GEN-LAST:event_SaveFileBtnActionPerformed

    private void SaveAsFilebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SaveAsFilebtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "You clicked save as file with your latest changes");
    }//GEN-LAST:event_SaveAsFilebtnActionPerformed

    private void PrintFilebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PrintFilebtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "You clicked print file");
    }//GEN-LAST:event_PrintFilebtnActionPerformed

    private void PicturebtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_PicturebtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Select an area on the page and insert an image there");
    }//GEN-LAST:event_PicturebtnActionPerformed

    private void SocialbtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SocialbtnActionPerformed
        // TODO add your handling code here:
        //JOptionPane.showMessageDialog(this, "It's FaceBook time");
        JOptionPane.showMessageDialog(this, "Share the file on a social network");
    }//GEN-LAST:event_SocialbtnActionPerformed

    private void AddFileBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_AddFileBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "You clicked add a new file from device");
    }//GEN-LAST:event_AddFileBtnActionPerformed

    private void SignInBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_SignInBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "You clicked sign in");
    }//GEN-LAST:event_SignInBtnActionPerformed

    private void ZoomingBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ZoomingBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Increase/Decrease the zoom level");
    }//GEN-LAST:event_ZoomingBtnActionPerformed

    private void UseCursorBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UseCursorBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Select text for copying or adding comment");
    }//GEN-LAST:event_UseCursorBtnActionPerformed

    private void HighlightBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_HighlightBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "You clicked highlight Text");
    }//GEN-LAST:event_HighlightBtnActionPerformed

    private void CaptureBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CaptureBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "You clicked capture your screen");
    }//GEN-LAST:event_CaptureBtnActionPerformed

    private void UsePencilBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_UsePencilBtnActionPerformed
        // TODO add your handling code here:
        JOptionPane.showMessageDialog(this, "Create, manage and apply signatures");
    }//GEN-LAST:event_UsePencilBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Bai3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            @Override
            public void run() {
                new Bai3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton AddFileBtn;
    private javax.swing.JButton CaptureBtn;
    private javax.swing.JButton ExitBtn;
    private javax.swing.JButton HighlightBtn;
    private javax.swing.JLabel LabelToolbar;
    private javax.swing.JButton Picturebtn;
    private javax.swing.JButton PrintFilebtn;
    private javax.swing.JButton SaveAsFilebtn;
    private javax.swing.JButton SaveFileBtn;
    private javax.swing.JButton SecurityBtn;
    private javax.swing.JButton SignInBtn;
    private javax.swing.JButton Socialbtn;
    private javax.swing.JButton UseCursorBtn;
    private javax.swing.JButton UsePencilBtn;
    private javax.swing.JButton ZoomingBtn;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JButton openFileBtn;
    // End of variables declaration//GEN-END:variables
}
