/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package View;

import java.awt.event.KeyEvent;
import javax.swing.table.DefaultTableModel;
import java.sql.*;
import javax.swing.JOptionPane;

/**
 *
 * @author GIA KIET
 */
public class ThemSCDT extends javax.swing.JFrame {

    /**
     * Creates new form ThemSCDT
     */
    public ThemSCDT() {
        initComponents();
        HoTen.disable();
        Tentxt.disable();
        showCV();
        ShowDSCV();
    }
    DefaultTableModel tb1 = new DefaultTableModel();
    DefaultTableModel tb2 = new DefaultTableModel();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane3 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        Imeitxt = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        Tentxt = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        HoTen = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        NgL = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        ND = new javax.swing.JTextArea();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        DSCV = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        CV = new javax.swing.JTable();
        ThemBtn = new javax.swing.JButton();

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane3.setViewportView(jTable2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(0, 102, 102));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel1.setText("So IMEI");

        Imeitxt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        Imeitxt.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                ImeitxtKeyPressed(evt);
            }
        });

        jLabel2.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel2.setText("Ten DT");

        Tentxt.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel3.setText("Ho ten KH");

        HoTen.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel4.setText("Ngay lap");

        NgL.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        NgL.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                NgLKeyPressed(evt);
            }
        });

        jLabel5.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel5.setText("Noi dung ");

        ND.setColumns(20);
        ND.setRows(5);

        jLabel6.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel6.setText("Danh sach cong viec");

        jLabel7.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        jLabel7.setText("Danh sach cong viec sua chua");

        DSCV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(DSCV);

        CV.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        CV.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CVMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(CV);

        ThemBtn.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        ThemBtn.setText("Them");
        ThemBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                ThemBtnActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(Imeitxt, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(NgL, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(Tentxt, javax.swing.GroupLayout.PREFERRED_SIZE, 208, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(ND, javax.swing.GroupLayout.PREFERRED_SIZE, 232, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(12, 12, 12))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel6)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addGap(13, 13, 13)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 302, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jLabel7))
                                .addGap(75, 75, 75))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(ThemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 127, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE))))))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Imeitxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(Tentxt, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(42, 42, 42)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(HoTen, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(31, 31, 31)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(NgL, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(71, 71, 71)
                        .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(60, 60, 60)
                        .addComponent(ND, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(33, 33, 33)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel6, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7, javax.swing.GroupLayout.PREFERRED_SIZE, 42, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 204, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(ThemBtn, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void ImeitxtKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_ImeitxtKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            HoTen.setText("");
            Tentxt.setText("");
            Connection con = null;
            try {
                con = ConnectDB.getConn();
            } catch (Exception e) {
                e.printStackTrace();
            }
            int sl = 0;
            String sql = "SELECT HOTENKH, TENDT FROM DIENTHOAI WHERE IMEI = ?";
            try {
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, Imeitxt.getText());
                ResultSet rs = ps.executeQuery();
                if(rs.next()){
                    HoTen.setText(rs.getString("HOTENKH"));
                    Tentxt.setText(rs.getString("TENDT"));
                    sl += 1;
                }
                if(sl == 0)
                    JOptionPane.showMessageDialog(this, "Not Found");
            } catch(Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_ImeitxtKeyPressed

    private void NgLKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_NgLKeyPressed
        // TODO add your handling code here:
        if(evt.getKeyCode() == KeyEvent.VK_ENTER){
            ND.setText("");
            Connection con = null;
            try {
                con = ConnectDB.getConn();
            } catch (Exception e) {
                e.printStackTrace();
            }
            int sl = 0;
            String sql = "SELECT NOIDUNG FROM SUACHUA WHERE IMEI = ? AND NGAYLAP = ?";
            try {
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, Imeitxt.getText());
                ps.setString(2, NgL.getText());
                ResultSet rs = ps.executeQuery();
                if(rs.next()){
                    ND.setText(rs.getString("NOIDUNG"));
                    sl += 1;
                }
                if(sl == 0)
                    JOptionPane.showMessageDialog(this, "Not Found");
            } catch(Exception e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_NgLKeyPressed

    private void CVMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CVMouseClicked
        // TODO add your handling code here:
        long dg = 0;
        int selectedRow = CV.getSelectedRow();
        tb2 = (DefaultTableModel) DSCV.getModel();
        if(selectedRow >= 0 && selectedRow <= tb1.getRowCount()){
            Object[] row = new Object[2];
            Connection con = null;
            try {
                con = ConnectDB.getConn();
            } catch(Exception e) {
                e.printStackTrace();
            }
            String sql = "SELECT DONGIA FROM CONGVIEC WHERE MACV = ?";
            try {
                PreparedStatement ps = con.prepareStatement(sql);
                ps.setString(1, tb1.getValueAt(selectedRow, 0).toString());
                ResultSet rs = ps.executeQuery();
                if(rs.next()) {
                    dg = rs.getLong("DONGIA");
                }
            } catch (Exception e) {
                e.printStackTrace();
            }
            row[0] = tb1.getValueAt(selectedRow, 1);
            row[1] = dg;
            tb2.addRow(row);
        }
    }//GEN-LAST:event_CVMouseClicked

    private void ThemBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_ThemBtnActionPerformed
        // TODO add your handling code here:
        if(Imeitxt.getText().equals("") || NgL.getText().equals("")){
            JOptionPane.showMessageDialog(this, "Vui long nhap day du thong tin");
            return;
        } else {
            Connection con = null;
            try {
                con = ConnectDB.getConn();
            } catch(Exception e) {
                e.printStackTrace();
            }
            long dg = 0, sum = 0;
            String tencv = null;
            int sl = tb2.getRowCount();
            String MPSC = getMaPSC(Imeitxt.getText(), NgL.getText());
            for(int i=0; i<sl; i++){
                String sql = "INSERT INTO CT_SC(MAPSC, MACV) VALUES (?, ?)";
                try {
                    PreparedStatement ps = con.prepareStatement(sql);
                    ps.setString(1, MPSC);
                    tencv = tb2.getValueAt(i, 0).toString();
                    ps.setString(2, getMaCV(tencv));
                    int oke = ps.executeUpdate();
                    dg = Long.parseLong(tb2.getValueAt(i, 1).toString());
                    sum += dg;
                    if(oke == 0){
                        JOptionPane.showMessageDialog(this, "Failed");
                        sum -= dg;
                        return;
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            }
            
            if(sum > 0){
                String sql = "UPDATE SUACHUA SET TONGTIEN = ? WHERE MAPSC = ?";
                try {
                    PreparedStatement ps = con.prepareStatement(sql);
                    ps.setLong(1, sum);
                    ps.setString(2, MPSC);
                    int oke = ps.executeUpdate();
                    if(oke  > 0){
                        JOptionPane.showMessageDialog(this, "Success");
                        Imeitxt.setText("");
                        HoTen.setText("");
                        Tentxt.setText("");
                        NgL.setText("");
                        ND.setText("");
                        ShowDSCV();
                    } else {
                        JOptionPane.showMessageDialog(this, "Failed");
                        return;
                    }
                } catch (Exception e) {
                    e.printStackTrace();
                }
            } else {
                JOptionPane.showMessageDialog(this, "Failed");
                return;
            }
        }
    }//GEN-LAST:event_ThemBtnActionPerformed

    /**
     * @param args the command line arguments
     */
    
    public void showCV(){
        Connection con = null;
        try {
            con = ConnectDB.getConn();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        String sql = "SELECT MACV, TENCV FROM CONGVIEC";
        
        tb1.setColumnIdentifiers(new String[]{"Ma cong viec", "Ten cong viec"});
        tb1.setRowCount(0);
        try {
            PreparedStatement ps = con.prepareStatement(sql);
            ResultSet rs = ps.executeQuery();
            while(rs.next()){
                tb1.addRow(new String[] {rs.getString("MACV"), rs.getString("TENCV")});
            }
            CV.setModel(tb1);
        } catch(Exception e) {
            e.printStackTrace();
        }
        setVisible(true);
    }
    
    public void ShowDSCV(){
        tb2.setColumnIdentifiers(new String[]{"Ten cong viec", "Don Gia"});
        tb2.setRowCount(0);
        DSCV.setModel(tb2);
        setVisible(true);
    }
    
    public String getMaCV(String a) {
        Connection con = null;
        try{
            con = ConnectDB.getConn();
        } catch (Exception e) {
            e.printStackTrace();
        }
        
        String sql = "SELECT MACV FROM CONGVIEC WHERE TENCV = ?";
        
        try {
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, a);
            ResultSet rs = ps.executeQuery();
            if(rs.next()) 
                return rs.getString("MACV");
        } catch(Exception e) {
            e.printStackTrace();
        }
        return null;
    }
    
    public String getMaPSC(String a, String b){
        Connection con = null;
        try {
            con = ConnectDB.getConn();
        } catch (Exception e) {
            e.printStackTrace();
        } 
        String sql = "SELECT MAPSC FROM SUACHUA WHERE IMEI = ? AND NGAYLAP = ?";
        try {
            PreparedStatement ps = con.prepareStatement(sql);
            ps.setString(1, a);
            ps.setString(2, b);
            ResultSet rs = ps.executeQuery();
            if(rs.next())
                return rs.getString("MAPSC");
        } catch(Exception e) {
            e.printStackTrace();
        }
        return null;
    }
    
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ThemSCDT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ThemSCDT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ThemSCDT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ThemSCDT.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ThemSCDT().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTable CV;
    private javax.swing.JTable DSCV;
    private javax.swing.JTextField HoTen;
    private javax.swing.JTextField Imeitxt;
    private javax.swing.JTextArea ND;
    private javax.swing.JTextField NgL;
    private javax.swing.JTextField Tentxt;
    private javax.swing.JButton ThemBtn;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable2;
    // End of variables declaration//GEN-END:variables

    

}
